name: 'SCA Checkmarx Scan'

on:
  workflow_run:
    workflows: ["Manual deployment workflow"]
    types: [requested]

concurrency: checkmarx

jobs:
  checkmarx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo Source for SQ Scanning
      uses: actions/checkout@v2
    # Build sample Maven project
    #- name: Build Maven 
    #  run: mvn -f sample-sonarqube-project-src/pom.xml install
    # CheckMarx Github Action
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
      with:
        project: ${{env.PROJECT_NAME}}
        team: ${{env.TEAM_NAME}}
        break_build: false
        scanners: sca
        sca_tenant: ${{ secrets.CHECKMARX_SCA_TENANT_NAME }}
        sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }}
        sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }}
        # For Jira integration
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }}
      env:
        PROJECT_NAME: vtx-ui-mf-taxcat
        TEAM_NAME: /CxServer/CSE/TaxCat
        # exclude-folders: ".git/,test/,vertex-oseries-u*"
        # exclude-files: "pom.xml"