name: Run E2E Tests
on:
  push:
    branches: 
     - main
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ github.ref_name }}'
      - name: Build reports.json
        run: |
          git fetch origin gh-pages
          git checkout origin/gh-pages -- .
          node -e "
          const fs = require('fs');
          const dirs = fs.readdirSync('.', { withFileTypes: true })
            .filter(d => d.isDirectory()).map(d => d.name)
            .filter(name => /^\d{4}-\d{2}-\d{2}_\d{2}-\d{2}$/.test(name)); // only YYYY-MM-DD_HH-mm format
          fs.writeFileSync('reports.json', JSON.stringify(dirs.sort().reverse(), null, 2));
          console.log('reports.json generated:', dirs);
          "
      - name: Prepare site files
        run: |
          mkdir -p site-publish
          cp reports.json site-publish/
          cp allure-homepage.html site-publish/index.html
      - name: Deploy reports.json + index.html
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site-publish
          keep_files: true
      - name: Exit after upload
        run: exit 0
