name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
        
      - name: Install Typescript if using .ts config
        run: npm install --save-dev ts-node typescript
        
      - name: Run Cypresss from automation folder
        run: |
          export TS_NODE_PROJECT=apps/frontend/my-new-app-e2e/tsconfig.json
          npx cypress run --config-file=apps/frontend/my-new-app-e2e/cypress.config.ts
          
          
