name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
        
      - name: Install Typescript if using .ts config
        run: npm install --save-dev ts-node typescript
        
      - name: Run Cypresss from automation folder
        run: |
          npx ts-node --project apps/frontend/my-new-app-e2e/tsconfig.json node_modules/.bin/cypress run --config-file=apps/frontend/my-new-app-e2e/cypress.config.ts

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev
      
      - name: Generate Allure Reports
        run: |
          npx allure generate apps/frontend/my-new-app-e2e/allure-results --clean -o apps/frontend/my-new-app-e2e/allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
           name: allure-report
           path: apps/frontend/my-new-app-e2e/allure-report

      - name: Exit after upload
        run: exit 0
        
          
          
