name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
        
      - name: Install Typescript if using .ts config
        run: npm install -g typescript
        
      - name: Run Cypresss from automation folder
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress run --project apps/frontend/my-new-app-e2e --config-file=$(pwd)/apps//frontend/my-new-app-e2e/cypress.config.ts
          
          
