name: Run E2E Tests

on:
   workflow_dispatch:
     inputs:
       branch:
         description: 'Select the branch'
         required: true
         default: main
         type: choice
         options:
           - main
           - develop
       browser:
         description: 'Browser to run on'
         required: true
         default: 'electron'
         type: choice
         options:
           - electron
           - chrome
           - firefox
       environment:
         description: 'Environment for E2E'
         required: true
         default: 'staging'
         type: choice
         options:
           - staging
           - qa
           - prod

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
        
      - name: Install Typescript if using .ts config
        run: npm install --save-dev ts-node typescript
        
      - name: Run Cypresss from automation folder
        run: |
          npx ts-node --project apps/frontend/my-new-app-e2e/tsconfig.json node_modules/.bin/cypress run --config-file=apps/frontend/my-new-app-e2e/cypress.config.ts
        continue-on-error: true

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Debug:check allure-results folder exists
        run: ls -R
      
      - name: Generate Allure Reports
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: allure-results
           path: allure-results
           
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: allure-report
           path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_token: ${{secrets.GITHUB_TOKEN}}
           publish_branch: gh-pages
           publish_dir: allure-report

      - name: Exit after upload
        run: exit 0
        
          
          
